{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using Theano backend.\n",
      "WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:\n",
      " https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29\n",
      "\n",
      "INFO (theano.gof.compilelock): Waiting for existing lock by process '21814' (I am process '21799')\n",
      "INFO (theano.gof.compilelock): To manually release the lock, delete /users/mtaranov/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/lock_dir\n",
      "Using gpu device 1: GeForce GTX TITAN X (CNMeM is disabled, cuDNN None)\n"
     ]
    }
   ],
   "source": [
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import sys\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import MinMaxScaler, StandardScaler\n",
    "import copy\n",
    "sys.path.append('/users/mtaranov/LongRange3D/')\n",
    "from models_binnedFeat import LongRangeDNN\n",
    "from utils import get_features, get_labels, subsample_data, normalize_features, reconstruct_2d, printMatrix, binarize, zscore, get_2D, plot_prediction, change_scale "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "contacts='pe'\n",
    "path='/users/mtaranov/datasets_3d/by_chr_dist_matched_'+contacts+'/'\n",
    "X_train = get_features(path+'d0_X_train_thres_10.npy')\n",
    "y_train = get_labels(path+'d0_y_train_thres_10.npy')\n",
    "X_valid = get_features(path+'d0_X_valid_thres_10.npy')\n",
    "y_valid = get_labels(path+'d0_y_valid_thres_10.npy')\n",
    "X_test = get_features(path+'d0_X_test_thres_10.npy')\n",
    "y_test = get_labels(path+'d0_y_test_thres_10.npy')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "X_train_normalized, X_valid_normalized, X_test_normalized = normalize_features(X_train, X_valid, X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "((6710, 1, 10, 2), (1796, 1, 10, 2), (988, 1, 10, 2))"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train_normalized.shape, X_valid_normalized.shape, X_test_normalized.shape"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# without distance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Training model...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_3_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd16574a7d0>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd16574a7d0>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_3_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd16573fe90>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd16573fe90>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_2_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162ff4150>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162ff4150>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_2_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f8f650>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f8f650>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 1, 9, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_1_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f43c50>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f43c50>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 1, 9, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_1_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f59250>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f59250>()]')\n",
      "\n",
      "INFO (theano.gof.compilelock): Refreshing lock /users/mtaranov/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/lock_dir/lock\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuElemwise{mul,no_inplace}.0, convolution2d_3_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162fb5310>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162fb5310>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuElemwise{mul,no_inplace}.0, convolution2d_3_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd16574ad10>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd16574ad10>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuElemwise{mul,no_inplace}.0, convolution2d_2_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd165706950>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd165706950>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 100, 1, 1), filter_dilation=(1, 1)}(GpuElemwise{mul,no_inplace}.0, convolution2d_2_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f02a90>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f02a90>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 1, 9, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_1_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f12650>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f12650>()]')\n",
      "\n",
      "ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(local_conv_dnn,local_conv_gemm,local_abstractconv_cudnn,local_abstractconv3d_cudnn,local_abstractconv_gemm,local_abstractconv3d_gemm,local_abstractconv_gradweight_gemm,local_abstractconv3d_gradweight_gemm,local_abstractconv_gradinputs_gemm,local_abstractconv3d_gradinputs_gemm)\n",
      "ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(100, 1, 9, 1), filter_dilation=(1, 1)}(GpuFromHost.0, convolution2d_1_W)\n",
      "ERROR (theano.gof.opt): TRACEBACK:\n",
      "ERROR (theano.gof.opt): Traceback (most recent call last):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1982, in process_node\n",
      "    replacements = lopt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py\", line 1335, in transform\n",
      "    new_repl = opt.transform(node)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 3548, in local_abstractconv_cudnn\n",
      "    conv_mode=conv_mode)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 1186, in dnn_conv\n",
      "    return GpuDnnConv(algo=algo)(img, kerns, out, desc)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/dnn.py\", line 359, in __init__\n",
      "    if version() < (5000, 5000):\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py\", line 429, in dnn_version\n",
      "    profile=False)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function.py\", line 326, in function\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py\", line 486, in pfunc\n",
      "    output_keys=output_keys)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1795, in orig_function\n",
      "    defaults)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py\", line 1661, in create\n",
      "    input_storage=input_storage_lists, storage_map=storage_map)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/link.py\", line 699, in make_thunk\n",
      "    storage_map=storage_map)[:3]\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py\", line 1047, in make_all\n",
      "    impl=impl))\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 935, in make_thunk\n",
      "    no_recycling)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/op.py\", line 839, in make_c_thunk\n",
      "    output_storage=node_output_storage)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1190, in make_thunk\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1131, in __compile__\n",
      "    keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1586, in cthunk_factory\n",
      "    key=key, lnk=self, keep_lock=keep_lock)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 1159, in module_from_key\n",
      "    module = lnk.compile_cmodule(location)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py\", line 1489, in compile_cmodule\n",
      "    preargs=preargs)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/nvcc_compiler.py\", line 417, in compile_str\n",
      "    return dlimport(lib_filename)\n",
      "  File \"/users/mtaranov/local/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py\", line 302, in dlimport\n",
      "    rval = __import__(module_name, {}, {}, [module_name])\n",
      "ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.DnnVersion object at 0x7fd162f17ad0>(), '\\n', 'libcudnn.so.5: cannot open shared object file: No such file or directory', '[<theano.sandbox.cuda.DnnVersion object at 0x7fd162f17ad0>()]')\n",
      "\n"
     ]
    }
   ],
   "source": [
    "dnn_normalized = LongRangeDNN(num_features=9, use_deep_CNN=True)\n",
    "validation_data = (X_valid_normalized[:, :, :9, :], y_valid)\n",
    "dnn_normalized.train(X_train_normalized[:, :, :9, :], y_train, validation_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "print(dnn_normalized.test(X_test_normalized[:, :, :9, :], y_test))\n",
    "print(dnn_normalized.test(X_train_normalized[:, :, :9, :], y_train))\n",
    "print(dnn_normalized.test(X_valid_normalized[:, :, :9, :], y_valid))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#save model and weights\n",
    "dnn_normalized.save(contacts+'_dnn_Siamese_linear_genomic_features_'+'thres_'+thres, '/users/mtaranov/genome3D/')"
   ]
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python [default]",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
